---
title: "Alert Report"  
output: html_document
---
```{r,echo=FALSE}
##use following lines for standalone report testing
#tod <- Sys.time()
#inputArgs <- c("VmwVmCpuUtilizationHigh","vSphere2~2008S-WIN44",3,4,5,6)
#rtviewRestServer <- "localhost:8068"
```
***  
Generated @ *`r tod`*  

***

**DOMAIN NAME:**    `r inputArgs[1]`  
**ALERT NAME:**     `r inputArgs[2]`  
**ALERT INDEX:** `r inputArgs[3]`  
**ALERT ID:** `r inputArgs[4]`  
**ALERT SEVERITY:** `r inputArgs[5]`  
**ALERT TEXT:** `r inputArgs[6]`  

***
```{r, echo=FALSE, include=FALSE}
source("sl_utils.R")
alert_index <- unlist(strsplit(inputArgs[3],"~"))
alert_index
host <- getHistory(rtviewRestServer,alert_index[2],fcol="name",
                        cache="VmwVirtualMachines",package="vmwmon_rtvquery",
                        col="time_stamp;mem.usage.average;cpu.usage.average",tr=600)
library(ggplot2)
```
```{r, echo=FALSE}
#qplot(host_CPU$time_stamp,host_CPU$cpu.usage.average,ylim=c(0,100),geom="line",
#      main="CPU utilization at time of Alert", ylab="% CPU",
#     xlab=paste("Time (starting @ ",host_CPU$time_stamp[1],")",sep=""))

a <- ggplot(data=host, aes(x=time_stamp))
a <- a + geom_line(aes(y=cpu.usage.average, color="CPU")) + ylim(0.0,100.0)
a <- a + xlab(paste("Time (starting @ ",host$time_stamp[1],")",sep=""))
a <- a + ylab("% Utilization") + ggtitle("System Utilization at time of Alert")
a <- a + geom_line(data=host,aes(y=mem.usage.average, color="Memory"))
a <- a + scale_color_manual("",labels=c("CPU","Memory"),values=c("#00FF00","#0000CC"))
a
```

